#ifndef  _affichage_h_
#define _affichage_h_

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ Declarations des fonctions dans le .cpp $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
void affichageHeureNextion();
void affichePageEclairage();
void affichePageBrassage();
void affichePageConfig();
void affichePageHorloge();
void affichePageAlarme();
void affichePageInfo();
void affichePageMenu();
void affichePageTel();
void affichePageWifi();
void affichePageGraph7J();
void affichePageEtalonnage();
void affichePageSd();
void affichePagePopup();
void boutonCouleur1(void *ptr);
void boutonCouleur2(void *ptr);
void boutonCouleur3(void *ptr);
void boutonCouleur4(void *ptr);
void boutonBrassage1(void *ptr);
void boutonBrassage2(void *ptr);
void boutonBrassage3(void *ptr);
void boutonRefuge(void *ptr);
void boutonNourrissageManuel(void *ptr);
void boutonOnOffAlim1(void *ptr);
void boutonOnOffAlim2(void *ptr);
void boutonOnOffRemonte(void *ptr);
void boutonminBrassage1(void *ptr);
void boutonminBrassage2(void *ptr);
void boutonminBrassage3(void *ptr);
void boutonoscillo1(uint32_t valeur);
void boutonoscillo2(uint32_t valeur);
void boutonoscillo3(uint32_t valeur);
void boutonoscillo1max(void *ptr);
void boutonoscillo1min(void *ptr);
void boutonoscillo2max(void *ptr);
void boutonoscillo2min(void *ptr);
void boutonoscillo3max(void *ptr);
void boutonoscillo3min(void *ptr);
void boutonTempeteAleatoire(void *ptr);
void boutonTempeteManuel(void *ptr);
void boutonChangementDEau(void *ptr);
void boutonBuzzerMenu(void *ptr);
void boutonBuzzerAlarme(void *ptr);
void boutonPhRAC(void *ptr);
void soundBuzzerOn();
//void bouton
void versBasSd(void *ptr);
void versHautSd(void *ptr);
void effaceSd(void *ptr);
void redemarrage(void *ptr);
void restaure(void *ptr) ;
void effaceBufferTexte();
void effaceminuteEnTexteIn();
void avancementBarBrassage(uint8_t etape);
void enregistrerBrassage(void *ptr);
void avancementBarconfig(uint8_t etape);
void enregistrerConfig(void *ptr);
void enregistrerHorloge(void *ptr);
void enregistrerTel(void *ptr);
void enregistrerWifi(void *ptr);
void enregistrerEclairage(void *ptr);
void enregistrerAlarme(void *ptr);
void statutprogressbar(uint8_t etape, uint8_t totalEtape, uint8_t quelBar);
void horraireEnSeconde(uint32_t h, uint16_t d, uint16_t m);
void rafraichirBrassage1Nextion();
void rafraichirBrassage2Nextion();
void rafraichirBrassage3Nextion();
void rafraichirEclairageCouleur1Nextion();
void rafraichirEclairageCouleur2Nextion();
void rafraichirEclairageCouleur3Nextion();
void rafraichirEclairageCouleur4Nextion();
void rafraichirHeureSiSurMenu();
void rafraichirPhBacNextion();
void rafraichirRedoxNextion();
void rafraichirSaliniteNextion();
void rafraichirTemperatureBacNextion();
void rafraichirTemperatureRampeNextion();
void rafraichirIconeBatterie();
void rafraichirSignalWifi();
void rafraichirSignalGSM();
void rafraichirMesuresEtalonnage();
void rafraichirboutonalimentationmanuel();
void statutCouleur1();
void statutCouleur2();
void statutCouleur3();
void statutCouleur4();
void statutBrassage1();
void statutBrassage2();
void statutBrassage3();
void statutOnOffAlim1();
void statutOnOffAlim2();
void statutOnOffDelay();
void statutTempete();
void statutTempeteAleatoire();
void statutTempeteIconeAleatoire();
void statutChangementDEau();
void statutBuzzerOnOffMenu();
void statutBuzzerOnOffAlarme();
void statutOnOffRAC();
void statutRefuge();
void rafraichirIconeBatterie();
void statutNotifOnOff();
void tempeteNextion();
void iconNourrissageEnCours();
void versBrassage(void *ptr);
void versConfig(void *ptr);
void versHorloge(void *ptr);
void versAlarme(void *ptr);
void versInfo(void *ptr);
void versMenu(void *ptr);
void versTel(void *ptr);
void versEclairage(void *ptr);
void versWifi(void *ptr);
void versStandby(void *ptr);
void versChoixGraph(void *ptr);
void versGraph24H(void *ptr);
void versGraph7J(void *ptr);
void versEtalonnage(void *ptr);
void versSd(void *ptr);
void versPopup(void *ptr);
void calibreSonde(void *ptr);
void changementAdresseSonde(void *ptr);
void sondeACalibrer(void *ptr);
void lectureBoutons();
void effaceLesEvenementsSurLecranSd();
void texteProgmemAuNextion(NexText, const char texteEnProgmem[] PROGMEM, const uint16_t couleurTexte);
void texteAuNextion(NexText champTexte, char*texte, const uint16_t couleurTexte);
void graphique24H(uint16_t T, uint16_t bufT, uint16_t Ph, uint16_t bufPh, uint16_t redox, uint16_t bufRedox, float Salinite, float bufSalinite);
void graphique7J(uint16_t T, uint16_t Ph, uint16_t redox, float Salinite);

#endif
